- Gemfile
- Gemfile.lock
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- config/initializers/kaminari_config.rb
imagemagickは各自モデルにattachmentの記述をお願いします。
kaminariはテキスト通りにコンフィグとビューも生成してます。
> [Add]gem imagemagick,kaminari

- config/routes.rb
> Add routing

- app/assets/stylesheets/admins/items.scss
- app/controllers/admins/items_controller.rb
- app/controllers/admins/reviews_controller.rb
- app/models/application_record.rb
- app/models/review.rb
- app/views/admins/items/index.html.erb
- app/views/admins/reviews/index.html.erb
- db/seeds.rb
> Fix bug for seeds.rb

- app/assets/stylesheets/admins/items.scss
- app/assets/stylesheets/admins/sessions.scss
- app/controllers/admins/items_controller.rb
- app/controllers/admins/reviews_controller.rb
- app/models/application_record.rb
- app/models/item.rb
- app/models/review.rb
- app/views/admins/items/index.html.erb
- app/views/admins/items/new.html.erb
- app/views/admins/reviews/index.html.erb
- db/seeds.rb
- 他の部分にも干渉してしまう記述を修正しました
失礼しました。
> fix bug for scss

- app/controllers/users/orders_controller.rb
- app/views/layouts/_users_header.html.erb
- app/views/users/items/index.html.erb
- app/views/users/orders/index.html.erb
- app/views/users/orders/show.html.erb
> Feature orders/index,orders/show

- app/controllers/users/items_controller.rb
- app/controllers/users/orders_controller.rb
- app/controllers/users/users_controller.rb
- app/views/layouts/_users_header.html.erb
- app/views/users/items/index.html.erb
- app/views/users/items/show.html.erb
- app/views/users/orders/index.html.erb
- app/views/users/orders/show.html.erb
- app/views/users/users/show.html.erb
- db/migrate/20190811032840_devise_create_users.rb
ヘッダー：サインイン、サインアウトで表示切り替え、link_to実装
ヘッダー部分でサインインしてないとエラー出たので、作りました。
> Feature header

- app/controllers/admins/admin_comments_controller.rb
- app/controllers/admins/users_controller.rb
- app/controllers/users/users_controller.rb
- app/models/admin_comment.rb
- app/models/user.rb
- app/views/admins/users/index.html.erb
- app/views/admins/users/show.html.erb
- config/routes.rb
- db/migrate/20190819093347_create_admin_comments.rb
- db/schema.rb
- test/fixtures/admin_comments.yml
- test/models/admin_comment_test.rb
アドミン側のユーザ関連ページ・その他を作成しました。
[Create]
- view/admins/users/index
- view/admins/users/show
-  models/admin_comment
-  controller/admin_comments
[Edit]は色々
> Feature users -> Create admin/users file

- app/assets/stylesheets/admins/items.scss
- app/assets/stylesheets/admins/reviews.scss
- app/controllers/admins/items_controller.rb
- app/helpers/users/items_helper.rb
- app/models/item.rb
- app/views/admins/items/index.html.erb
> Feature admin item index

- app/controllers/users/carts_controller.rb
- app/controllers/users/orders_controller.rb
URL直入れ弾く機能Errorなので一旦Commentout
> Fix before_action

- app/assets/javascripts/users/order.js
- app/controllers/users/carts_controller.rb
- app/controllers/users/orders_controller.rb
- app/helpers/users/carts_helper.rb
- app/views/admins/orders/show.html.erb
- app/views/layouts/_users_header.html.erb
- app/views/users/carts/index.html.erb
- app/views/users/items/show.html.erb
- app/views/users/orders/new.html.erb
- app/views/users/orders/show.html.erb
feature-radio_button
　radio_buttonのdefault設定と送られるパラメータの調整
feature-before_action
　他人のページに飛ぶURL直入れ禁止
feature-what-sales_status
　”販売中”以外の商品を購入出来ないように設定
の三本立てです。
> Feature mix（第一回　機能実装品評会の修正）

- app/assets/javascripts/admins/item.js
- app/assets/stylesheets/admins/items.scss
- app/controllers/admins/admin_comments_controller.rb
- app/controllers/admins/admins_controller.rb
- app/controllers/admins/reviews_controller.rb
- app/controllers/admins/users_controller.rb
- app/views/admins/items/_item_form.html.erb
- app/views/admins/items/index.html.erb
- app/views/admins/reviews/index.html.erb
- app/views/layouts/_admins_header.html.erb
- app/views/layouts/_users_header.html.erb
- config/application.rb
- db/seeds.rb
記述が重複している箇所を修正
seedsのnot null error を修正
jsの起動タイミングを修正
> Feature bug fix

- app/assets/javascripts/users/order.js
- app/controllers/users/carts_controller.rb
- app/controllers/users/orders_controller.rb
- app/helpers/users/carts_helper.rb
- app/views/admins/orders/show.html.erb
- app/views/layouts/_users_header.html.erb
- app/views/users/carts/index.html.erb
- app/views/users/items/show.html.erb
- app/views/users/orders/new.html.erb
- app/views/users/orders/show.html.erb
購入確認ページで新規住所を空だと登録出来ないようにしました。
また、各ページにflash messageの表示設定をしました。
> Feature validation

- app/assets/javascripts/admins/item.js
- app/assets/stylesheets/admins/items.scss
- app/controllers/admins/admin_comments_controller.rb
- app/controllers/admins/admins_controller.rb
- app/controllers/admins/items_controller.rb
- app/controllers/admins/reviews_controller.rb
- app/controllers/admins/users_controller.rb
- app/models/artist.rb
- app/models/disc.rb
- app/models/genre.rb
- app/models/item.rb
- app/models/label.rb
- app/models/song.rb
- app/views/admins/items/_disc_fields.html.erb
- app/views/admins/items/_error_messages.html.erb
- app/views/admins/items/_item_form.html.erb
- app/views/admins/items/_song_fields.html.erb
- app/views/admins/items/index.html.erb
- app/views/admins/reviews/index.html.erb
- app/views/admins/sessions/new.html.erb
- app/views/layouts/_admins_header.html.erb
- app/views/layouts/_users_header.html.erb
- app/views/users/shared/_links.html.erb
- config/application.rb
- db/seeds.rb
> Add error message

- app/controllers/admins/admin_comments_controller.rb
- app/controllers/admins/users_controller.rb
- app/controllers/users/users_controller.rb
- app/models/admin_comment.rb
- app/models/delivery_address.rb
- app/views/admins/users/show.html.erb
- app/views/users/items/index.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/users/withdrawal.html.erb
- config/initializers/application_controller_renderer.rb
- config/routes.rb
Add flash_message to users/users#quit & admins/users#quit
Fix delivery_address#destroy
Add validation_option to DeliveryAddress
> Feature users Update users#quit and models.delivery_address

- app/views/admins/items/index.html.erb
- app/views/users/items/index.html.erb
- db/migrate/20190811032840_devise_create_users.rb
- db/schema.rb
- db/seeds.rb
> Add order to seeds

- app/assets/javascripts/users/order.js
- app/controllers/users/orders_controller.rb
- app/controllers/users/reviews_controller.rb
- app/controllers/users/users_controller.rb
- app/helpers/users/carts_helper.rb
- app/helpers/users/orders_helper.rb
- app/models/delivery_address.rb
- app/views/users/carts/index.html.erb
- app/views/users/orders/_new.html.erb
- app/views/users/orders/new.html.erb
- app/views/users/users/show.html.erb
- config/application.rb
orders/newページ
新規配送先を追加ボタンを押した時のJSを調整しました。
・注文を確定するボタンの表示・非表示切り替え削除
→z-index指定したページがフェードインするのでキャンセルを押さない限り注文確定ボタン押せない（検証でCSSを外すなどする利用客向けの愛はない）
・paymentがマイページに反映
→これによりマイページで編集した支払方法がラジオボタンのデフォルトになるように調整出来ました
> Feature order js

- app/controllers/users/sessions_controller.rb
- app/views/admins/users/index.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/users/_delivery_address_fields.html.erb
- app/views/users/users/edit.html.erb
- config/routes.rb
通常ログアウト後と退会処理後自動ログアウト後のメッセージ表示を分けることに成功しました。それだけのために朝8時からもう昼の12時です。成果としてはメッセージの表示分けだけですが、色々勉強になって基礎の底上げができた感じがしたので、ユーザ担当で良かったと思いました。終わり。
> Feature users, Finish users/users#quit

- app/controllers/users/reviews_controller.rb
- app/controllers/users/users_controller.rb
- app/views/admins/orders/index.html.erb
- app/views/layouts/_admins_header.html.erb
- app/views/users/orders/show.html.erb
- app/views/users/reviews/new.html.erb
> Feature review css

- app/assets/stylesheets/admins/items.scss
- app/assets/stylesheets/users/sign_up.scss
- app/models/item.rb
- app/views/admins/items/_item_form.html.erb
- app/views/admins/sessions/new.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/users/withdrawal.html.erb
登録、ログイン、退会画面のCSS適用
classがitem-pageとなっているのは作成済みの設定を使っているため
> Feature refactoring

- app/controllers/users/reviews_controller.rb
- app/controllers/users/users_controller.rb
- app/views/admins/orders/index.html.erb
- app/views/layouts/_admins_header.html.erb
- app/views/users/orders/show.html.erb
- app/views/users/reviews/edit.html.erb
- app/views/users/reviews/new.html.erb
> Feature reviews/edit

- app/assets/javascripts/users/order.js
- app/controllers/admins/orders_controller.rb
- app/controllers/users/items_controller.rb
- app/controllers/users/orders_controller.rb
- app/helpers/users/orders_helper.rb
- app/views/admins/orders/_index.html.erb
- app/views/admins/orders/_table.html.erb
- app/views/admins/orders/index.html.erb
- app/views/admins/orders/index.js.erb
注文一覧ページのページネーションの挙動がおかしいのを修正しました
> Feature fix admins/orders/index

- app/assets/stylesheets/admins/users.scss
- app/assets/stylesheets/users/users.scss
- app/models/user.rb
- app/views/admins/users/index.html.erb
- app/views/admins/users/show.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/users/_delivery_address_fields.html.erb
- app/views/users/users/_list.html.erb
- app/views/users/users/edit.html.erb
- app/views/users/users/show.html.erb
CSS for users/users#edit & #show, admins/users#show
> Update css for users/users#edit & #show, admins/users#show

- app/assets/javascripts/users/item.js
- app/assets/stylesheets/users/items.scss
- app/controllers/users/favorites_controller.rb
- app/views/users/items/index.html.erb
商品一覧のViewの変更点
・ページングに位置を中心に配置
・いいね削除のエラーの解消
・絞り込み機能のスクロールでの追尾機能（とりさんのパクりました）
・枠線の色を薄い色に変更
確認お願いします。
> Feature items

- app/assets/javascripts/users/item.js
- app/assets/stylesheets/users/items.scss
- app/views/users/items/index.html.erb
- app/views/users/users/_delivery_address_fields.html.erb
商品一覧のサイドバーの角を丸くして上下移動するようにしました。
JavaScriptの指定class名を変更したので注意
> Fix views/users/items/index

- app/views/users/items/index.html.erb
> fix view to items/index
